### PR TITLE
bump socket2 version

### PR DESCRIPTION
**Pull request by irvingoujAtDevolution**
As discussed in previous PR, we only bump the version of socket2 for now

### CODE REVIEW

**Comment by keepsimple1** [comment]
Looks like the new socket2 version requires rustc 1.63+. It's okay for us to bump up rustc version to 1.63.

**Comment by irvingoujAtDevolution** [comment]
> Looks like the new socket2 version requires rustc 1.63+. It's okay for us to bump up rustc version to 1.63.

updated

**Comment by keepsimple1** [comment]
To fix the build errors, you need to update the CI [build.yml](https://github.com/keepsimple1/mdns-sd/blob/42c94bbb66df55b876da35684718f119d126f2d8/.github/workflows/build.yml#L22) .

**Comment by keepsimple1** [comment]
@irvingoujAtDevolution thanks for your work. Will you have the bandwidth to finish this PR in a couple of days? The current build error is due to clippy warnings. (If you are too busy to work on this, I can apply the change in the next release time).

**Comment by irvingoujAtDevolution** [comment]
> @irvingoujAtDevolution thanks for your work. Will you have the bandwidth to finish this PR in a couple of days? The current build error is due to clippy warnings. (If you are too busy to work on this, I can apply the change in the next release time).

I will update it today, sorry for the long delay.

**Comment by irvingoujAtDevolution** [comment]
@keepsimple1 Updated rust version, fixed clippy warnings

**Review by keepsimple1 — APPROVED** [review]
Thank you for the update!  I learned something new as well from these clippy fixes. LGTM!

**Pull request merged**
