### PR TITLE
SRV TTL triggers timeout event

### PR DESCRIPTION
**Pull request by wfeii1980**
[issue 54](https://github.com/keepsimple1/mdns-sd/issues/54) Add ServiceEvent::ServiceInactive

### CODE REVIEW

**Comment by keepsimple1** [comment]
Thanks for your PR! Could you please describe the problem at hand?  

From the title, my understanding is that SRV TTL expired while PTR record was still valid because PTR has 75 mins TTL while SRV only has 2 mins TTL.   Is that the problem? 

If yes, I think the direct cause is that currently we checks [only PTR record](https://github.com/keepsimple1/mdns-sd/blob/4d719a3a47152b634a0314bfd9041690772b6e29/src/service_daemon.rs#L2126) for refresh due.   If we send out `TYPE_SRV` refresh query when SRV is due to refresh, will that solve your problem?

At the high level, I think if SRV TTL indeed expires (even with refresh), which means the server no longer exists for the service instance, we should generate `ServiceRemoved` as the service instance is no longer valid.  It seems to me `ServiceInactive` is too similar to `ServiceRemoved` and would cause confusions.

**Comment by wfeii1980** [comment]
Because I don't quite understand the difference between `PTR` and `SRV` timeout, I added a `ServiceInactive`.

**Comment by keepsimple1** [comment]
> Because I don't quite understand the difference between `PTR` and `SRV` timeout, I added a `ServiceInactive`.

Both `PTR` and `SRV` (and address records `A` / `AAAA`) are required to have a [complete service instance](https://github.com/keepsimple1/mdns-sd/blob/42c94bbb66df55b876da35684718f119d126f2d8/src/service_info.rs#L262). I think any of them timeout should generate the event `ServiceRemoved`.  Do you need to know which of them caused the `ServiceRemoved` ?  If yes, then we need to find a way to distinguish them.

**Comment by keepsimple1** [comment]
I added a draft PR #180 to address the issues here. Let me know what you think. @wfeii1980 . Thanks.

**Comment by keepsimple1** [comment]
I've updated the PR #180 to support your use case.  Would you please help check if that PR can: 

1. refresh SRV when the responder is alive.
2. trigger `ServiceRemoved` when the SRV expires and the responder no longer alive

Please let me know if any issues. Thanks!

**Comment by keepsimple1** [comment]
@wfeii1980 please let me know what do you think about PR #180 ?  Would it help your use case?

**Comment by wfeii1980** [comment]
very good!

**Comment by keepsimple1** [comment]
I've merged PR #180, which should have fixed this one. If you still have issues with SRV TTL triggers, please open a new issue, or re-open this one. Thanks!

**Pull request closed without merging**
