### PR TITLE
track IPv4 interfaces with sockets to support multiple LANs

### PR DESCRIPTION
**Pull request by keepsimple1**
Fix the issue #46 .   (It might also help fixing #47, need testing ) 

- Use a new struct `IntfSock` to link the interface with the socket.
- Only include the DNS `A` record of the same LAN as the outgoing interface.
- Use the same socket for receiving and sending on an interface.

### CODE REVIEW

**Comment by fufesou** [comment]
https://github.com/keepsimple1/mdns-sd/issues/46#issuecomment-1186483112
If `192.168.100.103` is not in [adresses](https://github.com/keepsimple1/mdns-sd/blob/946f04307e98bc1190cac68fba21f5968a5a87d0/src/service_info.rs#L25). A query from `192.168.100.102` will also be answered. The register responses to the browser without ip.
I'm not sure if it was intentional.

**Comment by keepsimple1** [comment]
I think this is the case of responding PTR query. I was not sure if should skip the service if no addrs in the LAN of interface. Now I think it's better to skip such service, i.e. not to send out answers if no address. This is also consistent with the announcing logic. I've updated the diff to reflect this. Let me know if makes sense / works for you.

**Comment by fufesou** [comment]
Great job! It works now.

**Comment by keepsimple1** [comment]
Thanks for helping test.

**Pull request merged**
